name: "Issue Template Configuration"
description: Configuration for issue templates
body:
  - type: markdown
    attributes:
      value: |
        This file defines the issue templates and contact links for the repository.
