# Configuration for issue templates
# Issue templates should be defined in separate YAML files in the .github/ISSUE_TEMPLATE/ directory,
# or use issue_templates (not issue-templates) if using config.yml for legacy compatibility.

